[package]
name = "rust_calculator"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
meval = "0.2"

[lib]
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3"
features = ["Window", "Document", "CanvasRenderingContext2d"]
